spring:
  config.activate.on-profile: azure
  application.name: lab05-azure-image
  main.web-application-type: none     # Do not start a web server.
  ai:
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
    model.image: azure-openai
    azure:
      openai:
        image:
          options:
            model: dall-e-3
            n: 1                  # number of images to generate.
            #            response_format: "URL"  # or b64_json
            size: 1792x1024       # or 1024x1024, 1024x1792
            style: natural        # or vivid