spring:
  application.name: lab02-azure
  main.web-application-type: none     # Do not start a web server.
  ai:
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
    model.chat: azure-openai
    azure:
      openai:
        chat:
          options:
            deployment-name: gpt-5-mini
            model: gpt-5-mini
            temperature: 1 #The sampling temperature to use that controls the apparent creativity of generated completions. Higher values will make output more random while lower values will make results more focused and deterministic. It is not recommended to modify temperature and top_p for the same completions request as the interaction of these two settings is difficult to predict.