spring:
  application.name: Lab01 OpenAI
  main.web-application-type: none     # Do not start a web server.
  ai:
    embedding.transformer.enabled: false  # SpringAI provides a default embeddings model.  Disable this to force the use of a different model.
    retry:
      max-attempts: 1
    model.embedding: openai
    openai:
      embedding:
        options:
          model: text-embedding-ada-002